// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SmartCompany.Models
{
    public partial class Customers
    {
        public Customers()
        {
            InverseReferredByNavigation = new HashSet<Customers>();
            Invoices = new HashSet<Invoices>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? ReferredBy { get; set; }

        public virtual Customers ReferredByNavigation { get; set; }
        public virtual ICollection<Customers> InverseReferredByNavigation { get; set; }
        public virtual ICollection<Invoices> Invoices { get; set; }
    }
}