// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SmartCompany.Models
{
    public partial class Employee
    {
        public int Id { get; set; }
        public string SystemGeneratedEmpNr { get; set; }
        public DateTime StartDate { get; set; }
        public string Role { get; set; }
        public bool IsActive { get; set; }
        public int PersonId { get; set; }

        public virtual Person Person { get; set; }
    }
}