// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SmartCompany.Models
{
    public partial class Invoices
    {
        public int Id { get; set; }
        public DateTime BillingDate { get; set; }
        public int CustomerId { get; set; }

        public virtual Customers Customer { get; set; }
    }
}