// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace SmartCompany.Models
{
    public partial class Person
    {
        public Person()
        {
            Employee = new HashSet<Employee>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public DateTime DateOfBirth { get; set; }
        public int? ModifiedBy { get; set; }

        public virtual ICollection<Employee> Employee { get; set; }
    }
}